import {
  HiOutlineFilter,
  HiOutlineEmojiHappy,
  HiOutlineTruck,
  HiOutlineDocumentText,
  HiOutlineFilm,
  HiOutlineScale,
  HiOutlineChartBar,
  HiOutlineCreditCard,
  HiOutlineHeart,
  HiOutlineShoppingCart,
  HiOutlineAcademicCap,
  HiOutlineShoppingBag,
  HiOutlineHome,
  HiOutlineShieldCheck,
  HiOutlineSparkles,
  HiOutlineRefresh,
  HiOutlineGift,
  HiOutlineReceiptTax,
  HiOutlineDotsCircleHorizontal,
  HiOutlineCurrencyDollar, // Salary
  HiOutlineBriefcase, // Freelancing
  HiOutlineArrowUp, // Interest
} from "react-icons/hi";

export const categoryIcons = {
  Any: <HiOutlineFilter className="text-indigo-400" />,
  Food: <HiOutlineEmojiHappy className="text-amber-400" />,
  Transport: <HiOutlineTruck className="text-blue-400" />,
  Bills: <HiOutlineDocumentText className="text-gray-400" />,
  Entertainment: <HiOutlineFilm className="text-purple-400" />,
  Debt: <HiOutlineScale className="text-rose-400" />,
  Investments: <HiOutlineChartBar className="text-emerald-400" />,
  EMI: <HiOutlineCreditCard className="text-yellow-400" />,
  Health: <HiOutlineHeart className="text-pink-400" />,
  Shopping: <HiOutlineShoppingCart className="text-orange-400" />,
  Education: <HiOutlineAcademicCap className="text-sky-400" />,
  Groceries: <HiOutlineShoppingBag className="text-lime-400" />,
  Rent: <HiOutlineHome className="text-cyan-400" />,
  Insurance: <HiOutlineShieldCheck className="text-teal-400" />,
  PersonalCare: <HiOutlineSparkles className="text-fuchsia-400" />,
  Subscriptions: <HiOutlineRefresh className="text-violet-400" />,
  Gifts: <HiOutlineGift className="text-red-400" />,
  Taxes: <HiOutlineReceiptTax className="text-amber-500" />,
  Miscellaneous: <HiOutlineDotsCircleHorizontal className="text-gray-500" />,
  Salary: <HiOutlineCurrencyDollar className="text-emerald-400" />,
  Freelancing: <HiOutlineBriefcase className="text-blue-400" />,
  Investments: <HiOutlineChartBar className="text-purple-400" />,
  Interest: <HiOutlineArrowUp className="text-amber-400" />,
  Gift: <HiOutlineGift className="text-pink-400" />,
  Others: <HiOutlineDotsCircleHorizontal className="text-gray-400" />,
};
export const categoryColors = {
  Food: "bg-amber-900/40 text-amber-400",
  Transport: "bg-blue-900/40 text-blue-400",
  Bills: "bg-gray-700/40 text-gray-300",
  Entertainment: "bg-purple-900/40 text-purple-400",
  Debt: "bg-red-900/40 text-red-400",
  Investments: "bg-emerald-900/40 text-emerald-400",
  EMI: "bg-yellow-900/40 text-yellow-400",
  Health: "bg-pink-900/40 text-pink-400",
  Shopping: "bg-orange-900/40 text-orange-400",
  Education: "bg-sky-900/40 text-sky-400",
  Groceries: "bg-lime-900/40 text-lime-400",
  Rent: "bg-cyan-900/40 text-cyan-400",
  Insurance: "bg-teal-900/40 text-teal-400",
  PersonalCare: "bg-fuchsia-900/40 text-fuchsia-400",
  Subscriptions: "bg-violet-900/40 text-violet-400",
  Gifts: "bg-rose-900/40 text-rose-400",
  Taxes: "bg-amber-800/40 text-amber-300",
  Miscellaneous: "bg-gray-800/40 text-gray-400",
  Salary: "bg-emerald-900/40 text-emerald-400",
  Freelancing: "bg-blue-900/40 text-blue-400",
  Investments: "bg-purple-900/40 text-purple-400",
  Interest: "bg-amber-900/40 text-amber-400",
  Gift: "bg-pink-900/40 text-pink-400",
  Others: "bg-gray-800/40 text-gray-400",
};
